config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    resources :visits, only: [:show]
  end

  scope :search do
    get '/', to: 'search#new'
    get '/results', to: 'search#show'
  end

  ActiveAdmin.routes(self)

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
    mount PgHero::Engine, at: "pghero"
    mount Delayed::Web::Engine, at: '/jobs'
  end

  resources :categories, only: [:show]
  resources :products, only: [:show, :edit, :update] do
    resource :reviews, only: [:create]
  end
  resources :attachments, only: [:destroy]

  scope :cart do
    get '/', to: 'shopping_cart#show', as: 'cart'
    post 'add/:id', to: 'shopping_cart#add_product', as: 'cart_add_item'
    post 'apply_coupon', to: 'shopping_cart#apply_coupon', as: 'apply_coupon'
    delete 'coupon', to: 'shopping_cart#remove_coupon', as: 'remove_coupon'
    patch '/update_qty/:id', to: 'shopping_cart#update_qty', as: 'update_qty'
    delete '/cart/item/:id', to: 'shopping_cart#remove_item', as: 'remove_item'
    get 'checkout', to: 'shopping_cart#checkout', as: 'checkout'
    post 'checkout', to: 'shopping_cart#process_checkout'
    scope :checkout do
      get 'success/:id', to: 'shopping_cart#checkout_success', as: 'checkout_success'
    end
  end

  get 'privacy_policy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'help', to: 'pages#help'

  namespace :api do
    get 'zip/:code', to: 'zip_codes#lookup'
    get 'geocode/:query', to: 'zip_codes#geocode'
  end

  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_secure_token

  validates :zip_code, postal_code: true

  before_save :parse_zip_code

  private

  def parse_zip_code
    if zip_code_changed?
      parsed_zip = Postjoy.find(zip_code)
      if parsed_zip
        self.latitude = parsed_zip[:latitude]
        self.longitude = parsed_zip[:longitude]
      end
    end
  end
end

app/models/ahoy/visit.rb
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true

  def visitor_visits
    self.class.where(visitor_token: visitor_token)
  end

  def visitor_total_visits_count
    visitor_visits.count
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def line_total
    product.price * qty
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :order_coupons
  has_many :orders, through: :order_coupons
end

app/models/login_activity.rb
class LoginActivity < ApplicationRecord
  belongs_to :user, polymorphic: true, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  visitable

  has_many :cart_items
  has_many :products, through: :cart_items

  has_many :order_coupons
  has_many :coupons, through: :order_coupons

  def subtotal
    total_cents = 0
    self.cart_items.each do |item|
      total_cents += item.line_total.cents
    end
    return Money.new(total_cents)
  end

  def discount_total
    if self.coupons.any?
      @coupon = self.coupons.first
      if @coupon.type == "Coupons::Dollar"
        return @coupon.value
      elsif @coupon.type == "Coupons::Percent"
        return subtotal * @coupon.value
      else
        return Money.new(0)
      end
    else
      return Money.new(0)
    end
  end

  def total
    subtotal - discount_total
  end
end

app/models/order_coupon.rb
class OrderCoupon < ApplicationRecord
  belongs_to :order
  belongs_to :coupon
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :orders, through: :cart_items
  has_many :reviews
  belongs_to :category
  has_many_attached :images
  monetize :price_cents

  validates :name, presence: true
  validates :description, presence: true
  validates :price_cents, presence: true

  def average_rating
    reviews.average(:rating) || 0
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :login_activities, as: :user
  has_many :addresses

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
  belongs_to :address

  validates :address, uniqueness: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def about
  end

  def privacy
  end

  def terms
  end

  def help
  end
end

app/controllers/reports/visits_controller.rb
class Reports::VisitsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :authenticate_admin_user!
  def show
    @visit = Ahoy::Visit.find_by(visit_token: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports/visits_helper.rb
module Reports::VisitsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/reports/visits/show.html.erb
<div class="container">
    <h1>Visit Report</h1>
    <p class="lead">ID: <%= @visit.visit_token %></p>
    <p><%= @visit.started_at %></p>
    <hr>

    <table class="table table-sm table-bordered">
        <tr>
            <th>Visitor ID</th>
            <td><%= @visit.visitor_token %> (<%= pluralize(@visit.visitor_total_visits_count, 'visit') %>)</td>
        </tr>

        <tr>
            <th>IP</th>
            <td><%= @visit.ip %></td>
        </tr>

        <tr>
            <th>User Agent</th>
            <td><%= @visit.user_agent %></td>
        </tr>

        <tr>
            <th>Referrer / Domain</th>
            <% if !!@visit.referrer || !!@visit.referring_domain %>
                <td><%= @visit.referrer %> / <%= @visit.referring_domain %></td>
            <% else %>
                <td>None</td>
            <% end %>
        </tr>

        <tr>
            <th>Landing Page</th>
            <td><%= @visit.landing_page %></td>
        </tr>

        <tr>
            <th>Browser / OS / Device Type</th>
            <td><%= @visit.browser %> / <%= @visit.os %> / <%= @visit.device_type %></td>
        </tr>

        <tr>
            <th>City, Region, Country</th>
            <td><%= @visit.city %>, <%= @visit.region %>, <%= @visit.country %></td>
        </tr>

        <tr>
            <th>UTM Source</th>
            <td><%= @visit.utm_source %></td>
        </tr>
    </table>

    <hr>
    <h2>All Visits From Same User</h2>
    <table class="table table-sm table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>ID</th>
          <th>Date</th>
          <th>IP</th>
          <th>Location</th>
          <th>Device Info</th>
        </tr>
      </thead>
      <tbody>
        <% @visit.visitor_visits.each do |vv| %>
          <tr>
            <td><%= link_to vv.id, reports_visit_path(vv.visit_token), class: 'btn btn-sm btn-primary' %></td>
            <td><%= vv.started_at %></td>
            <td><%= vv.ip %></td>
            <td><%= vv.city %>, <%= vv.region %>, <%= vv.country %></td>
            <td><%= vv.browser %> / <%= vv.os %> / <%= vv.device_type %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <hr>

    <h2><%= pluralize(@visit.events.count, "Event") %></h2>
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Action</th>
                <th>Properties</th>
            </tr>
        </thead>

        <tbody>
            <% @visit.events.each do |event| %>
                <tr>
                    <td><%= event.name %></td>
                    <td><%= pp event.properties %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>