config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    resources :visits, only: [:show]
  end

  scope :search do
    get '/', to: 'search#new'
    get '/results', to: 'search#show'
  end

  ActiveAdmin.routes(self)

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
    mount PgHero::Engine, at: "pghero"
    mount Delayed::Web::Engine, at: '/jobs'
  end

  resources :categories, only: [:show]
  resources :products, only: [:show, :edit, :update] do
    resource :reviews, only: [:create]
  end
  resources :attachments, only: [:destroy]

  scope :cart do
    get '/', to: 'shopping_cart#show', as: 'cart'
    post 'add/:id', to: 'shopping_cart#add_product', as: 'cart_add_item'
    post 'apply_coupon', to: 'shopping_cart#apply_coupon', as: 'apply_coupon'
    delete 'coupon', to: 'shopping_cart#remove_coupon', as: 'remove_coupon'
    patch '/update_qty/:id', to: 'shopping_cart#update_qty', as: 'update_qty'
    delete '/cart/item/:id', to: 'shopping_cart#remove_item', as: 'remove_item'
    get 'checkout', to: 'shopping_cart#checkout', as: 'checkout'
    post 'checkout', to: 'shopping_cart#process_checkout'
    scope :checkout do
      get 'success/:id', to: 'shopping_cart#checkout_success', as: 'checkout_success'
    end
  end

  get 'privacy_policy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'help', to: 'pages#help'

  namespace :api do
    get 'zip/:code', to: 'zip_codes#lookup'
    get 'geocode/:query', to: 'zip_codes#geocode'
  end

  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_order, except: [:checkout_success]
  skip_before_action :verify_authenticity_token, only: [:process_checkout]

  def show
  end

  def add_product
    if @order.cart_items.exists?(product_id: params[:id])
      @item = @order.cart_items.find_by(product_id: params[:id])
      @product = @item.product
      @item.qty += 1
      @item.save
    else
      @product = Product.find(params[:id])
      @order.products << @product
    end
    redirect_to cart_url, notice: "<b>#{@product.name}</b> added to cart!"
  end

  def apply_coupon
    return back_to_cart unless Coupon.exists?(code: coupon_params[:code])
    @coupon = Coupon.find_by_code(coupon_params[:code])
    return back_to_cart if @order.order_coupons.exists?(coupon_id: @coupon.id)
    @order.coupons << @coupon
    redirect_to cart_url, notice: 'Coupon applied!'
  end

  def remove_coupon
    @order.order_coupons.first.try(:destroy)
    redirect_to cart_url
  end

  def update_qty
    @item = Product.find(params[:id])
    @cart_item = @order.cart_items.where(product_id: @item.id).first
    @cart_item.update(qty_params) if @cart_item
  end

  def remove_item
    @cart_item = @order.cart_items.where(product_id: params[:id]).first
    @cart_item.destroy
    redirect_to cart_url
  end

  def checkout
    if @order.cart_items.count === 0
      redirect_to cart_url, notice: 'Your cart has no items.'
    end
  end

  def process_checkout
    raise IncompleteAddress if address_empty?
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @order.total.cents,
      :description => "PetStore - Order #{@order.id}",
      :currency    => 'usd',
      :metadata    => {
        id: @order.id,
        subtotal: @order.subtotal,
        total: @order.total
      },
      :statement_descriptor => "PET STORE PURCHASE"
    )

    @order.update!(completed: true, payment_id: charge.id, charge: charge.to_h)
    @order.update!(order_params)
    OrdersMailer.success(@order).deliver_later!
    reset_session
    redirect_to checkout_success_url(charge.id), notice: 'Order success'
    # session[:order_id] = nil


  rescue Stripe::CardError => e
    flash[:error] = e.message
    render :checkout
  rescue IncompleteAddress
    render :checkout
  end

  def checkout_success
    @order = Order.find_by(payment_id: params[:id])
  end

  private

  def create_order
    @order = Order.create(ip_address: request.remote_ip)
    session[:order_id] = @order.id
  end

  def get_order
    @order = Order.find(session[:order_id])
  end

  def set_order
    if session[:order_id]
      get_order
    else
      create_order
    end
  end

  def coupon_params
    params.require(:coupon).permit(:code)
  end

  def qty_params
    params.require(:cart_item).permit(:qty)
  end

  def back_to_cart
    redirect_to cart_url, alert: 'Error adding coupon'
  end

  def order_params
    params.require(:order).permit!
  end

  def address_empty?
    order_params[:address].blank? || order_params[:city].blank? || order_params[:state].blank? || order_params[:zip].blank?
  end

  class IncompleteAddress < StandardError; end;
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/shopping_cart/_coupon_form.html.erb
<% if order.coupons.any? %>
	<p class="lead">You have applied the following coupon: <%= order.coupons.first.code %></p>
	<p><%= link_to "( Remove Coupon )", remove_coupon_path, method: :delete %></p>
<% else %>
	<%= simple_form_for :coupon, url: apply_coupon_path, method: :post do |f| %>
		<%= f.input :code, label: 'Discount Code' %>
		<%= f.submit 'Apply Coupon', class: 'btn btn-success' %>
	<% end %>
<% end %>

app/views/shopping_cart/checkout.html.erb
<div class="container">
	<h1>Checkout</h1>
	<h3>SUBTOTAL: <%= @order.total.format %> <span class="text-muted">(<%= pluralize(@order.cart_items.count, 'item') %>)</span></h3>
	<%= form_with model: @order, url: '', method: :post do |f| %>
		<div class="form-group">
			<label for="order[name]">Name</label>
			<%= f.text_field :name, class: 'form-control' %>
		</div>

		<div class="form-group">
			<label for="order[email]">Email</label>
			<%= f.text_field :email, class: 'form-control' %>
		</div>

		<div class="form-group">
			<label for="order[address]">Address</label>
			<%= f.text_field :address, class: 'form-control' %>
		</div>

		<div class="form-group">
			<label for="order[city]">City</label>
			<%= f.text_field :city, class: 'form-control' %>
		</div>

		<div class="form-group">
			<label for="order[state]">State</label>
			<%= f.select :state, options_for_select(us_states), {}, {class: 'form-control custom-select'} %>
		</div>

		<div class="form-group">
			<label for="order[zip]">ZIP</label>
			<%= f.text_field :zip, class: 'form-control' %>
		</div>

		<h5>Order Summary</h5>
		<ul>
			<% @order.cart_items.each do |ci| %>
				<li><%= ci.product.name %> x <%= ci.qty %> = <%= ci.line_total.format %></li>
			<% end %>
		</ul>

		<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Order <%= @order.id %>"
          data-amount="<%= @order.total.cents %>"
          data-locale="auto"></script>
	<% end %>
</div>

<script type="text/javascript">
	(function() {
	    $('form > input').keyup(function() {
	    	console.log(this);
	        var empty = false;
	        $('form > input').each(function() {
	            if ($(this).val() == '') {
	                empty = true;
	            }
	        });

	        if (empty) {
	            $('.stripe-button-el').attr('disabled', 'disabled'); // updated according to http://stackoverflow.com/questions/7637790/how-to-remove-disabled-attribute-with-jquery-ie
	        } else {
	            $('.stripe-button-el').removeAttr('disabled'); // updated according to http://stackoverflow.com/questions/7637790/how-to-remove-disabled-attribute-with-jquery-ie
	        }
	    });
	})()
</script>

app/views/shopping_cart/checkout_success.html.erb
<div class="container">
	<h1>Success!</h1>
	<hr>
	<h4 class="text-muted">Order #<%= @order.id %></h4>

	<h2>Payment Details</h2>
	Method: <%= @order.charge['source']['brand'] %> &mdash; <%= @order.charge['source']['last4'] %>
	<br>
	Amount: <%= @order.total.format %>
	<h2>Customer Address</h2>
	<p>
		<%= @order.name.upcase %> <br>
		<%= @order.address.upcase %> <br>
		<%= @order.city.upcase %>, <%= @order.state.upcase %> <%= @order.zip %>
	</p>

	<h2>Items</h2>
	<table class="table">
		<thead>
			<tr>
				<th>Product</th>
				<th>Quantity</th>
				<th>Unit Price</th>
				<th>Line Total</th>
			</tr>
		</thead>

		<tbody>
			<% @order.cart_items.each do |item| %>
				<tr>
					<td><%= item.product.name %></td>
					<td><%= item.qty %></td>
					<td><%= item.product.price.format %></td>
					<td><%= item.line_total.format %></td>
				</tr>
			<% end %>
			<tr>
				<td colspan="2"></td>
				<td class="text-muted">Discount</td>
				<td class="text-muted"><%= @order.discount_total.format %></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/shopping_cart/show.html.erb
<div class="container">
	<h1>Shopping Cart</h1>
	<div class="card">
		<div class="card-header bg-info text-white">
			<%= pluralize(@order.cart_items.count, 'items') %> in cart.
		</div>
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<th>Item</th>
					<th>Quantity</th>
					<th>Unit Price</th>
					<th>Line Total</th>
				</tr>
			</thead>

			<tbody>
				<% @order.cart_items.each do |item| %>
					<tr>
						<td><%= item.product.name %></td>
						<td>
							<%= form_with model: item, url: update_qty_path(item.product.id), local: false, method: :patch, class: 'form-inline' do |f| %>
								<div class="form-group">
									<%= f.text_field :qty, class: 'form-control qty-field' %>
								</div>
								<div class="form-group">
									<%= f.submit 'update', class: 'btn btn-primary' %>
								</div>
							<% end %>
							<%= link_to '(x)', remove_item_path(item.product.id), method: :delete %>
						</td>
						<td><%= item.product.price.format %></td>
						<td id="lt-<%= item.product.id %>"><%= item.line_total.format %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<% if @order.cart_items.count > 0 %>
		<span class="text-center"><%= link_to 'Checkout Now', checkout_path, class: 'btn btn-lg btn-primary' %></span>
	<% end %>
	<hr>
	<div class="row card-group">
		<div class="col-md-6">
			<div class="card border-success mb-3">
				<div class="card-header">
					Add Coupon
				</div>
				<div class="card-body">
					<%= render 'coupon_form', order: @order %>
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="card border-primary mb-3">
				<div class="card-header">
					Order Totals
				</div>

				<table class="table table-sm">
					<tr>
						<th>Subtotal</th>
						<td id="subtotal"><%= @order.subtotal.format %></td>
					</tr>
					<tr>
						<th>Discount</th>
						<td id="discount">&minus;<%= @order.discount_total.format %></td>
					</tr>
					<tr>
						<th>Order Total</th>
						<td class="order-total" id="total"><%= @order.total.format %></td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	
	
	
</div>

app/views/shopping_cart/update_qty.js.erb
<% if @cart_item %>
  alert('updated');
  $('#subtotal').html("<%= @order.subtotal.format %>");
  $('#discount').html("<%= @order.discount_total.format %>");
  $('#total').html("<%= @order.total.format %>");
  $('#lt-<%= @cart_item.product_id %>').html("<%= @cart_item.line_total.format %>");
<% else %>
  alert('error');
<% end %>