config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    resources :visits, only: [:show]
  end

  scope :search do
    get '/', to: 'search#new'
    get '/results', to: 'search#show'
  end

  ActiveAdmin.routes(self)

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
    mount PgHero::Engine, at: "pghero"
    mount Delayed::Web::Engine, at: '/jobs'
  end

  resources :categories, only: [:show]
  resources :products, only: [:show, :edit, :update] do
    resource :reviews, only: [:create]
  end
  resources :attachments, only: [:destroy]

  scope :cart do
    get '/', to: 'shopping_cart#show', as: 'cart'
    post 'add/:id', to: 'shopping_cart#add_product', as: 'cart_add_item'
    post 'apply_coupon', to: 'shopping_cart#apply_coupon', as: 'apply_coupon'
    delete 'coupon', to: 'shopping_cart#remove_coupon', as: 'remove_coupon'
    patch '/update_qty/:id', to: 'shopping_cart#update_qty', as: 'update_qty'
    delete '/cart/item/:id', to: 'shopping_cart#remove_item', as: 'remove_item'
    get 'checkout', to: 'shopping_cart#checkout', as: 'checkout'
    post 'checkout', to: 'shopping_cart#process_checkout'
    scope :checkout do
      get 'success/:id', to: 'shopping_cart#checkout_success', as: 'checkout_success'
    end
  end

  get 'privacy_policy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'help', to: 'pages#help'

  namespace :api do
    get 'zip/:code', to: 'zip_codes#lookup'
    get 'geocode/:query', to: 'zip_codes#geocode'
  end

  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_secure_token

  validates :zip_code, postal_code: true

  before_save :parse_zip_code

  private

  def parse_zip_code
    if zip_code_changed?
      parsed_zip = Postjoy.find(zip_code)
      if parsed_zip
        self.latitude = parsed_zip[:latitude]
        self.longitude = parsed_zip[:longitude]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def line_total
    product.price * qty
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :order_coupons
  has_many :orders, through: :order_coupons
end

app/models/login_activity.rb
class LoginActivity < ApplicationRecord
  belongs_to :user, polymorphic: true, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  visitable

  has_many :cart_items
  has_many :products, through: :cart_items

  has_many :order_coupons
  has_many :coupons, through: :order_coupons

  def subtotal
    total_cents = 0
    self.cart_items.each do |item|
      total_cents += item.line_total.cents
    end
    return Money.new(total_cents)
  end

  def discount_total
    if self.coupons.any?
      @coupon = self.coupons.first
      if @coupon.type == "Coupons::Dollar"
        return @coupon.value
      elsif @coupon.type == "Coupons::Percent"
        return subtotal * @coupon.value
      else
        return Money.new(0)
      end
    else
      return Money.new(0)
    end
  end

  def total
    subtotal - discount_total
  end
end

app/models/order_coupon.rb
class OrderCoupon < ApplicationRecord
  belongs_to :order
  belongs_to :coupon
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :orders, through: :cart_items
  has_many :reviews
  belongs_to :category
  has_many_attached :images
  monetize :price_cents

  validates :name, presence: true
  validates :description, presence: true
  validates :price_cents, presence: true

  def average_rating
    reviews.average(:rating) || 0
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :login_activities, as: :user
  has_many :addresses

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
  belongs_to :address

  validates :address, uniqueness: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def about
  end

  def privacy
  end

  def terms
  end

  def help
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update]
  before_action :authenticate_admin_user!, only: [:edit, :update]

  def show
    @review = @product.reviews.new
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Update success.'
    else
      redirect_to edit_product_path(@product), notice: 'Error updating product.'
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:description)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :set_search_query
  before_action :record_search, only: [:show]
  def new
    @q =  Product.ransack(params[:q])
  end

  def show
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).includes(:category)
  end

  private

  def record_search
    ahoy.track "Site search", params[:q]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/products/edit.html.erb
<div class="container">
	<h2>Editing: <small><%= @product.name %></small></h2>
	<hr>
	<%= form_with(model: @product, method: :patch, local: true) do |form| %>
	  <div class="field">
	    <%= form.label :description %>
	    <%= form.rich_text_area :description %>
	  </div>
	  <input type="submit">
	<% end %>
</div>

app/views/products/show.html.erb
<%= render 'shared/category_nav' %>
<div class="container">

  <div class="row">

    <div class="col-lg-3">
      <br>
      <div class="card">
        <h6 class="card-header">More Info</h6>
        <div class="card-body">
          <%= link_to 'Add To Cart', cart_add_item_path(@product.id), method: :post %>
        </div>
      </div>
    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div class="card mt-4">
        <% if @product.images.any? %>
          <%= image_tag url_for(@product.images.first.variant(resize: "900x400")) %>
        <% else %>
          <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
        <% end %>
        <div class="card-body">
          <h3 class="card-title"><%= @product.name %></h3>
          <h4><%= @product.price.format %></h4>
          <p class="card-text"><%= @product.description %></p>
          <span class="text-warning"><%= raw("&#9733;" * @product.average_rating) %> <%= raw("&#9734;" * (5 - @product.average_rating)) %> <!--&#9733; &#9733; &#9733; &#9734;--></span>
          <%= @product.average_rating %> stars
        </div>
      </div>
      <!-- /.card -->

      <div class="card card-outline-secondary my-4">
        <div class="card-header">
          Product Reviews
        </div>

        <div class="card-body">
          <% @product.reviews.each do |review| %>
            <% next unless review.persisted? %>
             <p><%= review.body %></p>
            <small class="text-muted"><%= raw("&#9733;" * review.rating) %> &mdash; Posted by <%= review.user.full_name %> on <%= review.created_at.strftime('%m/%d/%Y') %></small>
            <hr>
          <% end %>
          <% if user_signed_in? %>
           <%= form_with model: @review, url: product_reviews_path(@product), method: :post, local: true do |f| %>
              <div class="form-group">
                <label for="body">Message</label>
                <%= f.text_area :body, class: 'form-control' %>
              </div>
              <div class="form-group">
                <label for="rating">Rating</label>
                <% #f.number_field :rating, class: 'form-control' %>
                <% [1,2,3,4,5].each do |rating| %>
                  <%= f.radio_button(:rating, rating) %>
                  <%= f.label(:rating, rating.to_s) %>
                <% end %>
              </div>
              <div class="form-group">
                <%= f.submit 'Submit Review', class: 'btn btn-success' %>
              </div>
            <% end %>
          <% else %>
            <p class="lead">Please sign in to leave a review.</p>
          <% end %>
        </div>
      </div>
      <!-- /.card -->

    </div>
    <!-- /.col-lg-9 -->

  </div>

</div>