config/routes.rb
Rails.application.routes.draw do

  namespace :reports do
    resources :visits, only: [:show]
  end

  scope :search do
    get '/', to: 'search#new'
    get '/results', to: 'search#show'
  end

  ActiveAdmin.routes(self)

  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
    mount PgHero::Engine, at: "pghero"
    mount Delayed::Web::Engine, at: '/jobs'
  end

  resources :categories, only: [:show]
  resources :products, only: [:show, :edit, :update] do
    resource :reviews, only: [:create]
  end
  resources :attachments, only: [:destroy]

  scope :cart do
    get '/', to: 'shopping_cart#show', as: 'cart'
    post 'add/:id', to: 'shopping_cart#add_product', as: 'cart_add_item'
    post 'apply_coupon', to: 'shopping_cart#apply_coupon', as: 'apply_coupon'
    delete 'coupon', to: 'shopping_cart#remove_coupon', as: 'remove_coupon'
    patch '/update_qty/:id', to: 'shopping_cart#update_qty', as: 'update_qty'
    delete '/cart/item/:id', to: 'shopping_cart#remove_item', as: 'remove_item'
    get 'checkout', to: 'shopping_cart#checkout', as: 'checkout'
    post 'checkout', to: 'shopping_cart#process_checkout'
    scope :checkout do
      get 'success/:id', to: 'shopping_cart#checkout_success', as: 'checkout_success'
    end
  end

  get 'privacy_policy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'
  get 'help', to: 'pages#help'

  namespace :api do
    get 'zip/:code', to: 'zip_codes#lookup'
    get 'geocode/:query', to: 'zip_codes#geocode'
  end

  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_secure_token

  validates :zip_code, postal_code: true

  before_save :parse_zip_code

  private

  def parse_zip_code
    if zip_code_changed?
      parsed_zip = Postjoy.find(zip_code)
      if parsed_zip
        self.latitude = parsed_zip[:latitude]
        self.longitude = parsed_zip[:longitude]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def line_total
    product.price * qty
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :order_coupons
  has_many :orders, through: :order_coupons
end

app/models/login_activity.rb
class LoginActivity < ApplicationRecord
  belongs_to :user, polymorphic: true, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  visitable

  has_many :cart_items
  has_many :products, through: :cart_items

  has_many :order_coupons
  has_many :coupons, through: :order_coupons

  def subtotal
    total_cents = 0
    self.cart_items.each do |item|
      total_cents += item.line_total.cents
    end
    return Money.new(total_cents)
  end

  def discount_total
    if self.coupons.any?
      @coupon = self.coupons.first
      if @coupon.type == "Coupons::Dollar"
        return @coupon.value
      elsif @coupon.type == "Coupons::Percent"
        return subtotal * @coupon.value
      else
        return Money.new(0)
      end
    else
      return Money.new(0)
    end
  end

  def total
    subtotal - discount_total
  end
end

app/models/order_coupon.rb
class OrderCoupon < ApplicationRecord
  belongs_to :order
  belongs_to :coupon
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :orders, through: :cart_items
  has_many :reviews
  belongs_to :category
  has_many_attached :images
  monetize :price_cents

  validates :name, presence: true
  validates :description, presence: true
  validates :price_cents, presence: true

  def average_rating
    reviews.average(:rating) || 0
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :login_activities, as: :user
  has_many :addresses

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user
  belongs_to :address

  validates :address, uniqueness: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def about
  end

  def privacy
  end

  def terms
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_fit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<span class="text-muted">
			&copy; <%= DateTime.now.year %> Zachary Nusbaum
		</span>
		<span class="text-muted">
			&mdash; <%= link_to 'Privacy Policy', privacy_policy_path %>
		</span>
		<span class="text-muted">
			&mdash; <%= link_to 'Terms of Use', terms_path %>
		</span>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Pet Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cart', cart_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Help', help_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name || 'User' %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit Account', edit_user_registration_path, class: 'dropdown-item' %>
            <% if current_user.admin? %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Store Admin', admin_root_path, class: 'dropdown-item' %>
              <%= link_to 'Business Analytics', blazer_path, class: 'dropdown-item' %>
              <%= link_to 'Database Admin', rails_db_path, class: 'dropdown-item' %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Logout', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login/Register', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
      <!--
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      -->

    </ul>
    <%= search_form_for @q, url: results_path, method: :get, class: 'form-inline my-2 my-lg-0' do |f| %>
      <%= f.search_field :name_or_description_cont, class: 'form-control mr-sm-2', placeholder: 'Search' %>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/help.html.erb
<div class="container">
	<h1>Help</h1>
	<hr>
    <div class="row">
        <div class="col-10 mx-auto">
            <div class="accordion" id="faqExample">
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              Q: How does this work?
                            </button>
                          </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#faqExample">
                        <div class="card-body">
                            Add items to your cart. Then, proceed to checkout.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h5 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                          Q: How can I test the payment processor?
                        </button>
                      </h5>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#faqExample">
                        <div class="card-body">
                            <em>Use this credit card number: "4242424242424242".</em> <br>The expiration date can be any future date. The CVC code can be any 3-digit number.
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingThree">
                        <h5 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              Q. What is another question?
                            </button>
                          </h5>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#faqExample">
                        <div class="card-body">
                            The answer to the question can go here.
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--/row-->
</div>
<!--container-->

app/views/pages/home.html.erb
<%= render 'shared/category_nav' %>
<!-- Page Content -->
<div class="container home">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h1 class="display-3">A Warm Welcome!</h1>
    <p class="lead">Welcome to <i>Ozzy and Dez' Pet Store! We carry a large selection of pet products for all of your needs.</i></p>
  </header>

  <!-- Page Features -->
  <h4 class="text-center">Featured Items</h4>
  <div class="row text-center">
  	<div class="card-deck">
  	<% Product.all.where(featured: true).limit(4).each do |product| %>
		<!--<div class="col-lg-3 col-md-6 mb-4">-->
	      <div class="card">
	      	<% if product.images.any? %>
	      		<img class="card-img-top2" src="<%= url_for(product.images.first.variant(resize: "200x200")) %>" alt="">
	      	<% else %>
	      		<img class="card-img-top2" src="http://placehold.it/200x200" alt="">
	      	<% end %>

	        <div class="card-body">
	          <h4 class="card-title"><%= product.name %></h4>
	          <p class="card-text"><%= truncate strip_tags(product.description), length: 75 %></p>
	          <h5><%= product.price.format %></h5>
	          <p class="text-center"><%= link_to 'Details', product_path(product), class: 'btn btn-primary btn-sm' %></p>
	        </div>
	        <div class="card-footer">
	        	<div class="btn-group">
	        		<%= link_to 'Add to Cart', cart_add_item_path(product.id), method: :post, class: 'btn btn-success btn-sm' %>
	        		<%= link_to 'Buy Now', 'javascript:alert("Not yet implemented.")', class: 'btn btn-info btn-sm' %>
	        	</div>
	        </div>
	      </div>
	    <!--</div>-->
  	<% end %>
  </div>
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/shared/_category_nav.html.erb
<div class="category_nav">
	<ul class="nav bg-success">
	  <% Category.all.each do |category| %>
	    <li class="nav-item">
	      <a class="nav-link text-light" href="<%= category_path(category) %>"><%= category.name %></a>
	    </li>
	  <% end %>
	</ul>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
  	<%= raw(value) %>
  </div>
<% end %>